### ISSUE TITLE
bower install not working

### ISSUE THREAD

**Issue by abielikesu** [asafdav/ng-flags#11]
Hi asafdav,

Please create a new release (or tag? not sure what Bower uses) to make the regular bower command work:

bower install ng-flags

At the moment, I am having to run the install with the latest commit hash:

bower install https://github.com/asafdav/ng-flags.git#8790b86bc9

On another note, are you planning to have the css files as part of the package, instead of the external dependency?

Regards,
Abie

**Comment by asafdav** [comment]
Hi, thanks. 
I released a new version. let me know if it works.
